export const FOUR_SYMBOLS = [
  { id: 'azure', name: '青龙', element: '木', direction: '东', color: '#22c55e', season: '春' },
  { id: 'vermilion', name: '朱雀', element: '火', direction: '南', color: '#ef4444', season: '夏' },
  { id: 'white', name: '白虎', element: '金', direction: '西', color: '#94a3b8', season: '秋' },
  { id: 'black', name: '玄武', element: '水', direction: '北', color: '#3b82f6', season: '冬' },
]

export const THREE_ENCLOSURES = [
  { id: 'ziwei', name: '紫微垣', meaning: '天帝居所', range: '北天中央' },
  { id: 'taiwei', name: '太微垣', meaning: '天庭政府', range: '紫微垣东北' },
  { id: 'tianshi', name: '天市垣', meaning: '天街集市', range: '紫微垣东南' },
]

export const TWENTY_EIGHT_MANSIONS = [
  { id: 'jiao', name: '角木蛟', symbol: '角', mansion: 1, symbolId: 'azure', lucky: true, remark: '青龙首宿，主造化权柄' },
  { id: 'kang', name: '亢金龙', symbol: '亢', mansion: 2, symbolId: 'azure', lucky: true, remark: '主朝仪礼制' },
  { id: 'di', name: '氐土貉', symbol: '氐', mansion: 3, symbolId: 'azure', lucky: false, remark: '主宫殿寝庙' },
  { id: 'fang', name: '房日兔', symbol: '房', mansion: 4, symbolId: 'azure', lucky: true, remark: '主布政布政' },
  { id: 'xin', name: '心月狐', symbol: '心', mansion: 5, symbolId: 'azure', lucky: false, remark: '主明堂布政' },
  { id: 'wei1', name: '尾火虎', symbol: '尾', mansion: 6, symbolId: 'azure', lucky: true, remark: '主后宫后妃' },
  { id: 'ji', name: '箕水豹', symbol: '箕', mansion: 7, symbolId: 'azure', lucky: false, remark: '主口舌是非' },
  { id: 'dou', name: '斗木獬', symbol: '斗', mansion: 8, symbolId: 'black', lucky: true, remark: '主延寿增年' },
  { id: 'niu', name: '牛金牛', symbol: '牛', mansion: 9, symbolId: 'black', lucky: false, remark: '主祠祀祭祀' },
  { id: 'nu', name: '女土蝠', symbol: '女', mansion: 10, symbolId: 'black', lucky: false, remark: '主妇人嫁娶' },
  { id: 'xu', name: '虚日鼠', symbol: '虚', mansion: 11, symbolId: 'black', lucky: false, remark: '主哭泣丧事' },
  { id: 'wei2', name: '危月燕', symbol: '危', mansion: 12, symbolId: 'black', lucky: false, remark: '主宗庙祭祀' },
  { id: 'shi', name: '室火猪', symbol: '室', mansion: 13, symbolId: 'black', lucky: true, remark: '主宫殿缮修' },
  { id: 'bi1', name: '壁水貐', symbol: '壁', mansion: 14, symbolId: 'black', lucky: true, remark: '主文章秘籍' },
  { id: 'kui', name: '奎木狼', symbol: '奎', mansion: 15, symbolId: 'white', lucky: false, remark: '主武库兵甲' },
  { id: 'lou', name: '娄金狗', symbol: '娄', mansion: 16, symbolId: 'white', lucky: true, remark: '主兴兵聚众' },
  { id: 'wei3', name: '胃土雉', symbol: '胃', mansion: 17, symbolId: 'white', lucky: true, remark: '主仓廪五谷' },
  { id: 'mao', name: '昴日鸡', symbol: '昴', mansion: 18, symbolId: 'white', lucky: false, remark: '主丧服狱事' },
  { id: 'bi2', name: '毕月乌', symbol: '毕', mansion: 19, symbolId: 'white', lucky: true, remark: '主边兵弋猎' },
  { id: 'zui', name: '觜火猴', symbol: '觜', mansion: 20, symbolId: 'white', lucky: true, remark: '主收敛保藏' },
  { id: 'shen', name: '参水猿', symbol: '参', mansion: 21, symbolId: 'white', lucky: true, remark: '主斩杀伐谋' },
  { id: 'jing', name: '井木犴', symbol: '井', mansion: 22, symbolId: 'vermilion', lucky: true, remark: '主泉水酒食' },
  { id: 'gui', name: '鬼金羊', symbol: '鬼', mansion: 23, symbolId: 'vermilion', lucky: false, remark: '主祠祀死丧' },
  { id: 'liu', name: '柳土獐', symbol: '柳', mansion: 24, symbolId: 'vermilion', lucky: false, remark: '主厨膳饮食' },
  { id: 'xing', name: '星日马', symbol: '星', mansion: 25, symbolId: 'vermilion', lucky: true, remark: '主急事急事' },
  { id: 'zhang', name: '张月鹿', symbol: '张', mansion: 26, symbolId: 'vermilion', lucky: true, remark: '主珍宝宗庙' },
  { id: 'yi', name: '翼火蛇', symbol: '翼', mansion: 27, symbolId: 'vermilion', lucky: true, remark: '主文采乐府' },
  { id: 'zhen', name: '轸水蚓', symbol: '轸', mansion: 28, symbolId: 'vermilion', lucky: true, remark: '主车骑风散' },
]

export const FORTUNE_JUDGEMENT: Record<string, string> = {
  jiao: '角宿造作起田蚕，嫁娶婚姻福自然。开门放水招官职，世代荣华福满庭',
  kang: '亢宿造作旺田蚕，嫁娶婚姻进宝财。埋葬若然依此宿，为官代代位三公',
  di: '氐宿造作事如何，灾害重重不可过。埋葬婚姻俱不利，钱财用尽竟消磨',
  fang: '房宿造作旺蚕田，嫁娶婚姻福自天。埋葬开门皆吉利，儿孙荣贵寿绵绵',
  xin: '心宿造作损牛羊，三年两度主官方。埋葬婚姻皆不利，门中灾祸起萧墙',
  wei1: '尾宿造作旺田庄，六畜孳生旺蚕桑。嫁娶若能依此宿，儿孙世代产金梁',
  ji: '箕宿造作损钱财，三年两度被官灾。埋葬用之遭横祸，婚姻嫁娶不能谐',
  dou: '斗宿造作旺田蚕，世代儿孙近帝王。埋葬开门皆吉利，财珍宝货积如山',
  niu: '牛宿造作事如何，灾厄临门疾病多。埋葬婚姻俱不利，三年两度哭奈何',
  nu: '女宿造作损儿郎，女子招郎不久长。埋葬若还逢此宿，淹留灾祸两三场',
  xu: '虚宿造作主灾殃，男女孤眠不一双。内乱风声无礼节，儿孙媳妇伴人床',
  wei2: '危宿造作主惊惶，岁岁家中被贼伤。埋葬官灾不得免，重重丧祸两三场',
  shi: '室宿开门与放水，婚姻埋葬福皆来。田蚕六畜皆兴旺，世代为官到宰台',
  bi1: '壁宿开门放水良，婚姻埋葬旺田庄。儿孙代代为官贵，库满钱财谷满仓',
  kui: '奎宿造作不宜逢，埋葬婚姻不可从。若是开门并放水，无非世代主贫穷',
  lou: '娄宿造作旺田蚕，嫁娶婚姻福自然。埋葬开门皆吉利，儿孙世代锦衣鲜',
  wei3: '胃宿造作旺田蚕，富贵荣华福寿全。埋葬开门招百福，儿孙代代近天颜',
  mao: '昴宿造作损人口，灾害重重不可当。埋葬婚姻皆不利，招瘟惹祸主瘟癀',
  bi2: '毕宿造作旺田桑，嫁娶婚姻产贵郎。埋葬开门并放水，儿孙荣贵福难量',
  zui: '觜宿造作旺田蚕，埋葬婚姻富贵全。若得开门并放水，儿孙代代近君王',
  shen: '参宿造作旺田蚕，金玉重重积万千。埋葬开门皆吉利，儿孙世代锦衣旋',
  jing: '井宿造作旺田蚕，六畜孳生足米钱。埋葬婚姻皆吉利，儿孙世代享皇恩',
  gui: '鬼宿造作损儿郎，买卖经营财不来。埋葬婚姻俱不利，三年两度主悲哀',
  liu: '柳宿造作损家财，岁岁官灾不见谐。埋葬婚姻俱不利，蛇伤虎咬着人来',
  xing: '星宿造作旺田蚕，嫁娶婚姻出大官。埋葬若能依此宿，金银宝玉积如山',
  zhang: '张宿造作旺田蚕，富贵荣华福寿全。埋葬开门皆吉利，儿孙世代近天颜',
  yi: '翼宿造作旺田蚕，文武为官近帝王。埋葬开门皆吉利，儿孙世代坐朝堂',
  zhen: '轸宿造作旺田蚕，埋葬婚姻福禄全。开门放水皆吉利，儿孙世代近天颜',
}

export const XINGXIU_MANUAL = {
  title: '甘石星经',
  history: '甘公、石申著《星经》，著录一百四十六星官，八百余恒星。夜观天象二十八宿，以知人事休咎。高辛氏二子：阏伯主辰，实沈主参，始分野之制',
  principles: [
    '天有四象，以定四方',
    '二十八宿环周天，每日一宿值日',
    '月宿之位，本命之属',
    '观星知运，顺天应人',
  ],
  classics: [
    '天下太平，五星循度，不妄行',
    '岁星所在，国不可伐',
    '荧惑为勃乱，太白为兵革',
  ],
}
