version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'X1882'
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    reviewers:
      - 'X1882'
    labels:
      - 'github-actions'
      - 'dependencies'
    commit-message:
      prefix: 'ci'
      include: 'scope'
