export interface Creature {
  id: string
  name: string
  alias: string
  realm: 'shan' | 'hai' | 'huang' | 'tian'
  appearance: string
  habitat: string
  level: 'god' | 'king' | 'spirit' | 'beast' | 'monster'
  ability: string
  omen: string
  description: string
  color: string
  image: string
  stats: {
    power: number
    speed: number
    wisdom: number
    fortune: number
    ferocity: number
  }
}

export const CREATURES: Creature[] = [
  {
    id: 'dragon',
    name: '应龙',
    alias: '黄龙',
    realm: 'tian',
    appearance: '龙身有翼，鳞身脊棘',
    habitat: '凶犁土丘',
    level: 'god',
    ability: '蓄水降雨，画地成江',
    omen: '圣王出世则见',
    description: '黄帝神龙，杀蚩尤夸父，助大禹治水，龙之始祖也。',
    color: '#ffd700',
    image: '🐉',
    stats: { power: 100, speed: 90, wisdom: 95, fortune: 100, ferocity: 80 },
  },
  {
    id: 'phoenix',
    name: '凤凰',
    alias: '鸾鸟',
    realm: 'tian',
    appearance: '鸡头燕颔，蛇颈龟背',
    habitat: '丹穴之山',
    level: 'god',
    ability: '浴火重生，百鸟朝凤',
    omen: '天下太平则见',
    description: '非梧桐不栖，非竹实不食，非醴泉不饮，祥瑞之兆也。',
    color: '#f87171',
    image: '🦅',
    stats: { power: 90, speed: 95, wisdom: 100, fortune: 100, ferocity: 50 },
  },
  {
    id: 'kylin',
    name: '麒麟',
    alias: '仁兽',
    realm: 'shan',
    appearance: '麋身牛尾，狼蹄一角',
    habitat: '钟山',
    level: 'god',
    ability: '吐玉书，送贵子',
    omen: '圣人出世则见',
    description: '不踏生虫，不折生草，圣王在世则出。',
    color: '#4ade80',
    image: '🦌',
    stats: { power: 85, speed: 70, wisdom: 90, fortune: 100, ferocity: 10 },
  },
  {
    id: 'xuanwu',
    name: '玄武',
    alias: '玄冥',
    realm: 'hai',
    appearance: '龟蛇合体，玄甲缠身',
    habitat: '北海',
    level: 'god',
    ability: '玄冥控水，长寿不死',
    omen: '北方壬癸水之精',
    description: '北方七宿之精，主风雨，主寿命，镇北方。',
    color: '#3b82f6',
    image: '🐢',
    stats: { power: 75, speed: 40, wisdom: 85, fortune: 90, ferocity: 40 },
  },
  {
    id: 'baihu',
    name: '白虎',
    alias: '驺吾',
    realm: 'shan',
    appearance: '白毛黑纹，虎啸风生',
    habitat: '昆仑',
    level: 'god',
    ability: '主兵戈，镇西方',
    omen: '威猛之象',
    description: '西方庚金之精，主杀伐，辟邪祟，战神之象征。',
    color: '#f8fafc',
    image: '🐯',
    stats: { power: 95, speed: 85, wisdom: 60, fortune: 70, ferocity: 95 },
  },
  {
    id: 'zhuque',
    name: '朱雀',
    alias: '离朱',
    realm: 'tian',
    appearance: '赤如丹火，三足神鸟',
    habitat: '南极',
    level: 'god',
    ability: '离火炼心，接引登仙',
    omen: '南方丙丁火之精',
    description: '南方七宿之精，主文明，主礼仪，羽化飞升之引导者。',
    color: '#ef4444',
    image: '🦜',
    stats: { power: 85, speed: 100, wisdom: 75, fortune: 80, ferocity: 60 },
  },
  {
    id: 'qinglong',
    name: '青龙',
    alias: '苍龙',
    realm: 'tian',
    appearance: '苍鳞万点，角似鹿头似驼',
    habitat: '东方沧海',
    level: 'god',
    ability: '主宰雷霆，布雨兴云',
    omen: '东方甲乙木之精',
    description: '东方七宿之精，主生发，主仁政，四灵之首。',
    color: '#22c55e',
    image: '🐲',
    stats: { power: 95, speed: 90, wisdom: 85, fortune: 90, ferocity: 75 },
  },
  {
    id: 'taotie',
    name: '饕餮',
    alias: '狍鸮',
    realm: 'huang',
    appearance: '羊身人面，目在腋下',
    habitat: '钩吾之山',
    level: 'monster',
    ability: '吞噬万物，永不满足',
    omen: '贪婪之兆',
    description: '铜头铁额，食尽天下，上古四凶之一。',
    color: '#7c2d12',
    image: '👹',
    stats: { power: 90, speed: 50, wisdom: 30, fortune: 10, ferocity: 100 },
  },
  {
    id: 'gonggong',
    name: '共工',
    alias: '水神',
    realm: 'hai',
    appearance: '人面蛇身，朱发赤鳞',
    habitat: '天柱',
    level: 'king',
    ability: '洪水滔天，触山断柱',
    omen: '水患之兆',
    description: '与颛顼争帝，怒触不周山，天倾西北，地不满东南。',
    color: '#0ea5e9',
    image: '🌊',
    stats: { power: 95, speed: 60, wisdom: 40, fortune: 20, ferocity: 90 },
  },
  {
    id: 'jingwei',
    name: '精卫',
    alias: '帝女雀',
    realm: 'hai',
    appearance: '状如乌，文首白喙赤足',
    habitat: '发鸠之山',
    level: 'spirit',
    ability: '衔木石以填沧海',
    omen: '坚毅之象征',
    description: '炎帝之女，游于东海溺而不返，化为精卫，誓填沧海。',
    color: '#fb923c',
    image: '🐦',
    stats: { power: 5, speed: 70, wisdom: 50, fortune: 30, ferocity: 10 },
  },
  {
    id: 'kui',
    name: '夔牛',
    alias: '雷兽',
    realm: 'hai',
    appearance: '状如牛，苍身无角一足',
    habitat: '流波之山',
    level: 'king',
    ability: '出入水则必风雨，光如日月',
    omen: '雷霆之象征',
    description: '黄帝得之，以其皮为鼓，橛以雷兽之骨，声闻五百里。',
    color: '#1e3a5f',
    image: '🐃',
    stats: { power: 80, speed: 30, wisdom: 40, fortune: 60, ferocity: 70 },
  },
  {
    id: 'ninefox',
    name: '九尾狐',
    alias: '天狐',
    realm: 'shan',
    appearance: '狐身九尾，音如婴儿',
    habitat: '青丘之山',
    level: 'spirit',
    ability: '魅惑人心，百岁化人形',
    omen: '祥瑞或妖异',
    description: '太平则出为瑞，乱世则出为妖。食者不蛊。',
    color: '#f472b6',
    image: '🦊',
    stats: { power: 60, speed: 80, wisdom: 100, fortune: 70, ferocity: 40 },
  },
]

export const REALMS = {
  shan: { name: '山经', icon: '🏔️', color: '#22c55e' },
  hai: { name: '海经', icon: '🌊', color: '#3b82f6' },
  huang: { name: '荒经', icon: '🏜️', color: '#f59e0b' },
  tian: { name: '天经', icon: '⭐', color: '#d4af37' },
}

export const LEVELS = {
  god: { name: '神兽', color: '#ffd700' },
  king: { name: '兽王', color: '#c0c0c0' },
  spirit: { name: '灵物', color: '#a78bfa' },
  beast: { name: '异兽', color: '#22c55e' },
  monster: { name: '妖物', color: '#ef4444' },
}
