export const EIGHT_GATES = [
  { id: 'xiu', name: '休门', direction: '正北', element: '水', nature: '吉', note: '休养生息' },
  { id: 'sheng', name: '生门', direction: '东北', element: '土', nature: '大吉', note: '生生不息' },
  { id: 'shang', name: '伤门', direction: '正东', element: '木', nature: '凶', note: '损伤破坏' },
  { id: 'du', name: '杜门', direction: '东南', element: '木', nature: '平', note: '隐匿藏身' },
  { id: 'jing', name: '景门', direction: '正南', element: '火', nature: '小吉', note: '献策献计' },
  { id: 'si', name: '死门', direction: '西南', element: '土', nature: '大凶', note: '死绝之地' },
  { id: 'jing2', name: '惊门', direction: '正西', element: '金', nature: '凶', note: '惊恐虚诈' },
  { id: 'kai', name: '开门', direction: '西北', element: '金', nature: '大吉', note: '开运通达' },
]

export const FORMATIONS = [
  {
    id: 'bagua',
    name: '八卦阵',
    tier: '天阶',
    founder: '伏羲',
    effect: '八门金锁，万物化生',
    gates: ['kai', 'sheng', 'xiu', 'sheng', 'shang', 'du', 'si', 'jing'],
    power: 95,
    description: '伏羲氏观象授时，画八卦以通神明之德，以类万物之情。八卦成列，象在其中矣',
  },
  {
    id: 'liangyi',
    name: '两仪微尘',
    tier: '天阶',
    founder: '太清',
    effect: '一炁化三清',
    gates: ['kai', 'sheng'],
    power: 99,
    description: '太上老君所创，先天大道凝于微尘之中。一沙一世界，一叶一菩提，一微尘中藏三千大世界',
  },
  {
    id: 'zhuxian',
    name: '诛仙阵',
    tier: '天阶',
    founder: '通天',
    effect: '非圣必死',
    gates: ['si', 'shang'],
    power: 100,
    description: '诛仙、戮仙、陷仙、绝仙，四门剑阵。非入阵即死，非圣必亡',
  },
  {
    id: 'jiugong',
    name: '九宫八卦',
    tier: '地阶',
    founder: '诸葛',
    effect: '鱼入其中',
    gates: ['kai', 'sheng', 'xiu', 'shang', 'du', 'si', 'jing', 'jing2'],
    power: 88,
    description: '休生伤杜景死惊开，按休生景开四吉，伤杜惊死四凶',
  },
  {
    id: 'heaven',
    name: '天门阵',
    tier: '地阶',
    founder: '吕洞宾',
    effect: '飞龙在天',
    gates: ['kai', 'jing', 'sheng'],
    power: 82,
    description: '按青龙、白虎、朱雀、玄武四象布设。穆桂英大破天门阵',
  },
  {
    id: 'ten',
    name: '十绝阵',
    title: '地阶',
    founder: '金鳌岛',
    effect: '入阵绝命',
    gates: ['si', 'shang'],
    power: 85,
    description: '天绝、地裂、风吼、寒冰、金光、化血、烈焰、落魂、红水、红砂，十阵绝命',
  },
  {
    id: 'wan',
    name: '万仙阵',
    tier: '天阶',
    founder: '通天',
    effect: '万仙来朝',
    gates: ['kai', 'sheng', 'xiu'],
    power: 98,
    description: '截教终极阵法，诛仙阵升级。两仪、四象、八卦，万仙来朝',
  },
  {
    id: 'yellow',
    name: '黄河阵',
    tier: '天阶',
    founder: '三霄',
    founderTitle: '九曲黄河',
    gates: ['xiu', 'du'],
    power: 97,
    description: '九曲黄河，销铄元神，散仙入圣，仙体化为血水。削去顶上三花，消去胸中五气',
  },
  {
    id: 'yin',
    name: '太阴星主迷踪',
    tier: '地阶',
    founder: '太阴星君',
    effect: '太阴蔽日',
    gates: ['du', 'xiu'],
    power: 78,
    description: '太阴蔽日，星辰无光。入阵者神魂颠倒，不辨东西',
  },
  {
    id: 'hun',
    name: '混元一气',
    tier: '天阶',
    founder: '鸿钧',
    effect: '大道归一',
    gates: ['kai', 'sheng', 'xiu'],
    power: 100,
    description: '鸿蒙未判，混沌之初。道生一，一生二，二生三，三生万物',
  },
]

export const DIRECTIONS = ['坎', '艮', '震', '巽', '离', '坤', '兑', '乾']

export const ZHENFA_MANUAL = {
  title: '握奇经',
  history: '风后演握奇，经曰：大阵包小阵，大营包小营。隅落钩连，曲折相对。四为正，四为奇，余奇为握机',
  principles: [
    '八卦为体，八门为用',
    '四正四奇，变化无穷',
    '生开休生，四吉四凶',
    '奇正相生，循环无端',
  ],
  classics: [
    '堂堂之阵，正正之师',
    '兵形象水，水因地而制流',
    '兵无常势，水无常形',
  ],
}

export const TIER_COLORS: Record<string, string> = {
  '天阶': '#a855f7',
  '地阶': '#3b82f6',
  '人阶': '#22c55e',
}
